GET http://localhost:8000


###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

 {
    "name": "Pablo George",
    "email": "pablogeokar@hotmail.com",
    "password": "123456",
    "confirmPassword": "123456"
 }

###
POST http://localhost:8000/api/v1/auth/verify/email
Content-Type: application/json

 {
   "code": "3ccbe6c0da8249448e847f5ce"
 }

###
POST http://localhost:8000/api/v1/auth/password/forgot
Content-Type: application/json

 {
   "email": "pablogeokar@hotmail.com"
 }

###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email": "pablogeokar@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8000/api/v1/auth/refresh
